import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  title: 'Physical AI & Humanoid Robotics',
  tagline: 'A Comprehensive Guide to Embodied Intelligence',
  favicon: 'img/favicon.ico',

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // Set the production url of your site here
  url: 'https://your-username.github.io', // Update this with your GitHub Pages URL
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: '/physical-ai-humanoid-robotics-book/', // Update this with your project name

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: 'your-organization', // Usually your GitHub org/user name.
  projectName: 'physical-ai-humanoid-robotics-book', // Usually your repo name.

  onBrokenLinks: 'throw',

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            'https://github.com/your-organization/physical-ai-humanoid-robotics-book/edit/main/book/',

          // --- Custom Frontmatter Schema for Book Chapters (T015) ---
          // This serves as the documentation for the expected metadata fields in Markdown files.
          // Docusaurus automatically processes these fields from the Markdown frontmatter.
          //
          // Fields from data-model.md (BookChapter entity):
          // id: string (auto-generated by Docusaurus from filename/path, or can be set manually)
          // title: string (Chapter title - standard Docusaurus field)
          // description: string (Brief overview of the chapter content - standard Docusaurus field)
          // module_number: number (1-4, indicating which module this belongs to, e.g., `module_number: 1`)
          // duration_weeks: number (Estimated time to complete, in weeks, e.g., `duration_weeks: 2.5`)
          // prerequisites: string[] (Knowledge required before reading, e.g., `prerequisites: ["Python Basics", "ROS 2 Concepts"]`)
          // learning_objectives: string[] (Skills readers will gain, e.g., `learning_objectives: ["Understand Nodes", "Implement Publishers"]`)
          //
          // Example Frontmatter in a Markdown file:
          // ---
          // title: Introduction to ROS 2
          // description: Basic concepts of the Robot Operating System 2.
          // module_number: 1
          // duration_weeks: 1.0
          // prerequisites: ["Basic Python"]
          // learning_objectives: ["Understand ROS 2 Nodes", "Identify ROS 2 Topics"]
          // ---
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            'https://github.com/your-organization/physical-ai-humanoid-robotics-book/edit/main/book/',
          // Useful options to enforce blogging best practices
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: 'img/docusaurus-social-card.jpg',
    algolia: {
      // The application ID provided by Algolia
      appId: 'YOUR_APP_ID',
      // Public API key: it is safe to commit it
      apiKey: 'YOUR_SEARCH_API_KEY',
      indexName: 'YOUR_INDEX_NAME',
      // Optional: path for search page that doesn't use Algolia (e.g. `'/search'`)
      // contextualSearch: true,
      // Optional: Algolia search parameters
      // searchParameters: {},
      // Optional: path for search page that doesn't use Algolia (e.g. `'/search'`)
      // searchPagePath: 'search',
      // Optional: whether to include results from translation content
      // translations: {
      //   search: 'Search',
      //   noResults: 'No results found',
      //   loading: 'Loading...',
      //   // Add more translation keys as needed
      // },
    },
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Physical AI & Humanoid Robotics',
      logo: {
        alt: 'Physical AI Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'tutorialSidebar',
          position: 'left',
          label: 'Book',
        },
        {
          to: '/docs/module-1-ros-fundamentals/introduction-to-ros2',
          label: 'Start Reading',
          position: 'right'
        },
        {
          href: 'https://github.com/your-organization/physical-ai-humanoid-robotics-book',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Chapters',
          items: [
            {
              label: 'ROS 2 Fundamentals',
              to: '/docs/module-1-ros-fundamentals/introduction-to-ros2',
            },
            {
              label: 'Gazebo Simulation',
              to: '/docs/module-2-digital-twin/gazebo-simulation',
            },
            {
              label: 'NVIDIA Isaac Platform',
              to: '/docs/module-3-ai-robot-brain/isaac-sdk-overview',
            },
            {
              label: 'Conversational Robotics',
              to: '/docs/module-4-vision-language-action/whisper-integration',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'Discord',
              href: 'https://discordapp.com/invite/physical-ai',
            },
            {
              label: 'Twitter',
              href: 'https://x.com/physical_ai',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/your-organization/physical-ai-humanoid-robotics-book',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Physical AI & Humanoid Robotics Book. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['python', 'bash', 'json', 'yaml'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
